apiVersion: v1
kind: Service
metadata:
  name: crud-app-service
spec:
  type: NodePort
  selector:
    app: crud-app
  ports:
    - port: 3000          # Kubernetes service port
      targetPort: 3000    # Container port
      nodePort: 30080     # NodePort (external access)
